project:
  type: book
  output-dir: _book

book:
  title: "Bioinformatics Algorithms: From Scratch with Python"
  subtitle: "An Interactive Learning Approach Using Rosalind Problems"
  author: "Your Name"
  date: today
  
  chapters:
    - index.ipynb
    - part: "String Algorithms"
      chapters:
        - notebooks/BA1A.ipynb
        - notebooks/BA1B.ipynb
        - notebooks/BA1C.ipynb
    - part: "Motif Finding"
      chapters:
        - notebooks/BA2A.ipynb
    - part: "Graph Algorithms"  
      chapters:
        - notebooks/BA3A.ipynb

format:
  html:
    theme: cosmo
    code-fold: false
    code-tools: true
    toc: true
    number-sections: true
    highlight-style: github
    css: assets/custom.css
    
  pdf:
    documentclass: scrbook
    toc: true
    number-sections: true
    colorlinks: true

execute:
  freeze: auto
  cache: true
